config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "inicio", controller: "home", action: "index", as: "home"
  get "estudantes", to: "estudante#index", as: "estudantes"


  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estudante_controller.rb
class EstudanteController < ApplicationController
    def index
        @estudantes = 
        {nome: "Maria", idade: 20, curso: "Engenharia Civil"},
        {nome: "João", idade: 30, curso: "Engenharia Computação"},
        {nome: "Marcelo", idade: 42, curso: "Mecatronica"},
        {nome: "Alex", idade: 18, curso: "Biologia"}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @msg = "Estudando o Rails!"
    # render html: "<h2>Olá Mundo!</h2>".html_safe
    # render html: "<h2>#{@msg}</h2>".html_safe
    @author = "Fabio"
    @posts = [
        {title: "Rails", body: "Aprendendo com a OBC"},
        {title: "Javascript", body: "Aprendendo com a OBC"},
        {title: "Python", body: "Aprendendo com a OBC"},
        {title: "Go", body: "Aprendendo com a OBC"}

    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/estudante/index.html.erb
<div class="container">
    <h2 style="text-align:center;">Informações dos Estudantes</h2>
    <hr>

    <% @estudantes.each do |estudante|%>
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%=estudante[:nome]%>" aria-expanded="true" aria-controls="collapseOne">
                <%= estudante [:nome] %>
            </button>
            </h2>
            <div id="collapse<%=estudante[:nome]%>" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <p><%= estudante [:idade] %> Anos</p>
                <p><%= estudante [:curso] %></p>
        </div>
    </div>
  </div>
</div>
    <% end %>
</div>

app/views/home/index.html.erb
<div class="container">
    <h2 style="text-align:center;">Posts</h2>
    <hr>


    <h3>Admin: <%= @author %></h3>
    <ul class="list-group">
    <% @posts.each do |post|%>
        <li class="list-group-item">
            <%= post[:title]%> - <%= post[:body]%> 
        </li>
    <% end %>
    </ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Rails Blog", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
           <%= link_to "Estudantes", estudantes_path, class:"nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar"%>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>